### ISSUE TITLE
Broken Member Pages with latest BP and nouveau theme

### ISSUE THREAD

**Issue by svenl77** [Themekraft/BuddyForms-Members#24]
BuddyPress Settings:
<img width="625" alt="bildschirmfoto 2019-01-18 um 09 45 02" src="https://user-images.githubusercontent.com/645567/51378778-d727b180-1b05-11e9-80fb-7768ee2c3aec.png">

List posts looks ok
<img width="1282" alt="bildschirmfoto 2019-01-18 um 09 44 05" src="https://user-images.githubusercontent.com/645567/51378779-d7c04800-1b05-11e9-87f4-affac2c16c0c.png">

Create and edit is broken.
<img width="1251" alt="bildschirmfoto 2019-01-18 um 09 43 58" src="https://user-images.githubusercontent.com/645567/51378781-d7c04800-1b05-11e9-98fa-fb701cbd7038.png">

If the edit or create buddyforms view is displayed the menu is broken and the form is under all.

**Comment by massfap** [comment]
I think this is an issue with the main BuddyForms project.  If you insert the shortcode for a form on a Buddypress page without BuddyForms-Members installed you see the same issue where `<div id="buddypress" class="buddypress-wrap bp-dir-hori-nav">` is below the nav instead of above.
