### ISSUE TITLE
The Member Type form element is broken.

### ISSUE THREAD

**Issue by svenl77** [Themekraft/BuddyForms-Members#27]
**Description**
If you go to a registration form and want to use the Member Type form element it is without any options. Only the advanced tab. 

**The steps to reproduce the issue**
1. Make sure BuddyPress/ BuddyForms Pro and BuddyForms Members Pro and BuddyPress  Member Types is Instaled and Activated.
2. Create some Member Types under Users/ BP Member Types
3. Go to a registration form or create a new one.
4. Select the Member Types Form Element
5. Open the Form Element options
6. No options are there to select the Member types. the Generalö Tab is missing

**Expected behavior**
Have options to select the Member Types allowed or to make it a hidden field.

**Screenshots**
<img width="1092" alt="Bildschirmfoto 2019-05-21 um 13 01 22" src="https://user-images.githubusercontent.com/645567/58097831-2ecb4c00-7bd0-11e9-90e1-ccd794ef852c.png">

**Comment by gfirem** [comment]
@njota08 what is the question for this
